from __future__ import annotations

import json
import logging
import os
import sys

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, from_json
from pyspark.sql.types import (
    DoubleType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from .constants import DEFAULT_SCHEMAS_DIR, KAFKA_BOOTSTRAP_SERVERS, SPARK_MASTER_URL
from .models.base import BaseModel
from .models.simple_lr import SimpleLinearRegression

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _clear_local_spark_env() -> None:
    """Clear Spark-related environment variables that can override runtime behavior."""

    spark_envars = [
        "SPARK_MASTER",
        "SPARK_HOME",
        "PYSPARK_HOME",
        "PYSPARK_DRIVER_PYTHON",
        "PYSPARK_PYTHON",
        "SPARK_CONF_DIR",
        "SPARK_LOG_DIR",
        "SPARK_LOCAL_DIRS",
        "SPARK_WORKER_DIR",
    ]
    for envar in spark_envars:
        if os.environ.pop(envar, None) is not None:
            logger.info("Removed environment variable override: %s", envar)


def process_batch(topics: list[str] | None = None):
    """
    Initializes a Spark session;
    Reads historical data from Kafka topics into structured DataFrames;
    Trains all registered machine learning models;
    and Output predictions.
    """
    logger.info("Starting Spark Batch Processing...")

    # Ensure no local Spark environment variables interfere with the SparkSession configuration
    _clear_local_spark_env()

    # Driver uses project venv on host.
    # Keep executor python set via Spark conf to avoid host-side PYSPARK_PYTHON lookup warnings.
    os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable

    # Initialize extensible models
    models: list[BaseModel] = [
        SimpleLinearRegression(),
    ]

    # Filter models by topics if specified
    if topics:
        models = [model for model in models if model.topic in topics]

    if not models:
        logger.warning("No models to process for the specified topics. Exiting.")
        return

    # 1. Set up SparkSession
    # Connect to the Spark standalone cluster specified in docker-compose
    # Make sure to use the Spark Kafka package for format('kafka')
    spark = (
        SparkSession.builder.appName("OpusBatchProcessing")
        .master(SPARK_MASTER_URL)
        .config("spark.driver.host", "host.docker.internal")
        .config("spark.driver.bindAddress", "0.0.0.0")
        .config("spark.pyspark.driver.python", sys.executable)
        .config("spark.pyspark.python", "python3")
        .config("spark.executor.instances", "1")
        .config("spark.executor.cores", "1")
        .config("spark.executor.memory", "512m")
        .config(
            "spark.jars.packages",
            "org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.2",
        )
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("WARN")

    type_mapping = {"double": DoubleType(), "long": LongType(), "string": StringType()}

    # Group models by topic to optimize Kafka reads
    models_by_topic: dict[str, list[BaseModel]] = {}
    for model in models:
        models_by_topic.setdefault(model.topic, []).append(model)

    for topic, topic_models in models_by_topic.items():
        logger.info(f"Processing batch for topic: {topic}")

        topic_schema_path = DEFAULT_SCHEMAS_DIR / f"{topic}.json"
        if not topic_schema_path.exists():
            logger.error(
                f"Schema not found at {topic_schema_path}. Skipping topic: {topic}."
            )
            continue

        with open(topic_schema_path, "r") as f:
            topic_schema_dict = json.load(f)

        # Build topic schema dynamically
        topic_schema = StructType(
            [
                StructField(
                    col_name, type_mapping.get(col_type.lower(), StringType()), True
                )
                for col_name, col_type in topic_schema_dict.items()
            ]
        )

        # Read from the Kafka topic generated by the Flink Streaming job
        try:
            dataframe_kafka = (
                spark.read.format("kafka")
                .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
                .option("subscribe", topic)
                .option("startingOffsets", "earliest")
                .option("endingOffsets", "latest")
                .load()
            )
        except Exception as err:
            logger.error(f"Failed to read from Kafka for topic `{topic}`: {err}")
            continue

        # Decode JSON value column from Kafka into typed columns
        dataframe_parsed = dataframe_kafka.select(
            from_json(
                col("value").cast("string"),
                topic_schema,
            ).alias("data")
        ).select("data.*")

        logger.info(
            f"Displaying schema elements consumed from Kafka for topic `{topic}`:"
        )
        dataframe_parsed.printSchema()

        logger.info(f"Displaying top 5 sample rows for topic `{topic}`:")
        if dataframe_parsed.count() == 0:
            logger.warning(
                f"No data found in the `{topic}` topic!\n"
                f"Please ensure the PyFlink streaming job is running and processing events."
            )
            continue

        dataframe_parsed.show(5)

        for model in topic_models:
            logger.info(
                f"Training model: `{model.name}` via topic `{topic}` using tickers {model.tickers}"
            )

            try:
                # Filter by model tickers if specified
                dataframe_model = dataframe_parsed
                if model.tickers:
                    dataframe_model = dataframe_parsed.filter(
                        col("ticker").isin(model.tickers)
                    )

                if dataframe_model.count() == 0:
                    logger.warning(
                        f"No data found for tickers {model.tickers} in topic `{topic}`"
                    )
                    continue

                model.fit(dataframe_model)

                logger.info(f"Generating predictions with {model.name}")
                predictions = model.predict(dataframe_model)
                predictions.show(10)

            except Exception as err:
                logger.error(f"Model `{model.name}` processing failed: {err}")

    logger.info("Batch processing sequence finished.")
    spark.stop()
